---
title: "experimental labels"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "labels"
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  message: false
  warning: false
---


# Setup

```{r}
#| label: setup

source("https://inkaverse.com/setup.r")
```

## Field-book

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1tqNI7-wBtEgbi_9fahcp5hUVrbRrasQ1totp7qwQ82s/edit?gid=889807040#gid=889807040" %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")

#> Google fonts: https://fonts.google.com/

font <- c("Merriweather Sans", "Permanent Marker", "Tillana")
huito_fonts(font)
```

## Labels 

```{r}
label <- fb %>%
  label_layout(size = c(5, 7)
               , border_color = "forestgreen"
               , border_width = 1
               ) %>%
  include_image(
    value = "design/logo untrm.png"
    , size = c(1.5, 1.5)
    , position = c(1, 6.7)
    ) %>% 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(4.9, 1)
    , position = c(2.5, 6.)
    ) %>% 
  include_barcode(
    value = "qrcode"
    , size = c(3.5, 3.5)
    , position = c(2.5, 3.5)
    ) %>% 
  include_text(value = "plots"
               , position = c(4.2, 6.7)
               , size = 10
               , color = "black"
               , font = font[3]
               ) %>% 
  include_text(value = "escarificacion"
               , position = c(2.5, 1.3)
               , size = 10
               , color = "blue"
               , font = font[1]
               , prefix = "Escarificación: "
               ) %>% 
 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(6.9, 1)
    , position = c(2.5, 0.4)
    # , opts = 'image_convert(type = "Grayscale")'
    ) 

label %>% label_print(mode = "preview")
```



```{r}
#| eval: false

label %>% 
  label_print(mode = "complete"
              # , filename = "design/labels"
              , paper = c(21, 29.7)
              , units = "cm"
              )
```

